revert cache clear

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -29,6 +29,20 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
+      - name: Install LibTorch and CCache
+        shell: bash
+        run: brew install libtorch ccache
+
+      - name: Create download and build directory
+        run: mkdir download build
+
+      - name: Setup Python
+        id: setup-python
+        uses: actions/setup-python@v2
+        with:
+          python-version: ${{ matrix.python }}
+          architecture: ${{ matrix.python_architecture }}
+
       - name: Prepare Python dependencies cache
         uses: actions/cache@v2
         id: pip-cache
@@ -47,6 +61,10 @@ jobs:
             !generate_licenses/bin
           key: ${{ runner.os }}-venv-libs-generate_licenses-${{ matrix.python }}-${{ matrix.python_architecture }}-${{ hashFiles('**/requirements.txt', '**/requirements-dev.txt') }}
 
+      - name: Prepare Python venv for licenses.json generation
+        shell: bash
+        run: python -m venv generate_licenses
+
       - name: Prepare Python venv for building VOICEVOX engine cache
         uses: actions/cache@v2
         id: venv-build-voicevox-cache
@@ -56,12 +74,52 @@ jobs:
             !build_voicevox/bin
           key: ${{ runner.os }}-venv-libs-build_voicevox-${{ matrix.python }}-${{ matrix.python_architecture }}-${{ matrix.voicevox_core_version }}-${{ matrix.voicevox_core_example_version }}-${{ hashFiles('**/requirements.txt', '**/requirements-dev.txt') }}
 
+      - name: Prepare Python venv for building VOICEVOX engine
+        shell: bash
+        run: python -m venv build_voicevox
+
+      - name: Install dependencies for licenses.json generation
+        if: steps.venv-generate-licenses-cache.outputs.cache-hit != 'true'
+        shell: bash
+        run: |
+          source generate_licenses/bin/activate
+          pip install --upgrade pip setuptools wheel
+          pip install -r requirements-dev.txt
+          deactivate
+
+      - name: Generate licenses.json
+        shell: bash
+        run: |
+          source generate_licenses/bin/activate
+          python generate_licenses.py > licenses.json
+          deactivate
+
       - name: Prepare VOICEVOX Core cache
         uses: actions/cache@v2
         id: voicevox-core-cache
         with:
           key: ${{ matrix.os }}-voicevox-core-${{ matrix.voicevox_core_version }}
           path: download/core
+
+      - name: Download VOICEVOX Core
+        if: steps.voicevox-core-cache.outputs.cache-hit != 'true'
+        shell: bash
+        run: |
+          curl -L "https://github.com/Hiroshiba/voicevox_core/releases/download/${{ matrix.voicevox_core_version }}/core.zip" > download/core.zip
+          ditto -x -k --sequesterRsrc --rsrc download/core.zip download/
+          rm download/core.zip
+
+      - name: Prepare VOICEVOX Core file
+        if: steps.voicevox-core-cache.outputs.cache-hit != 'true'
+        shell: bash
+        run: mv libcore_cpu.dylib libcore.dylib
+        working-directory: download/core
+
+      - name: Export VOICEVOX Core path to LD_LIBRARY_PATH and LIBRARY_PATH
+        run: |
+          echo "LD_LIBRARY_PATH=$(pwd):${{ env.LD_LIBRARY_PATH }}" >> $GITHUB_ENV
+          echo "LIBRARY_PATH=$(pwd):${{ env.LIBRARY_PATH }}" >> $GITHUB_ENV
+        working-directory: download/core
 
       - name: Prepare VOICEVOX Core example cache
         uses: actions/cache@v2
@@ -70,11 +128,108 @@ jobs:
           key: ${{ matrix.os }}-voicevox-core-example-${{ matrix.voicevox_core_example_version }}
           path: download/voicevox_core_example
 
-      - name: Prepare VOICEVOX Core example cache
+      - name: Clone VOICEVOX Core example
+        if: steps.voicevox-core-example-cache.outputs.cache-hit != 'true'
+        shell: bash
         run: |
-          rm -rf generate_licenses
-          rm -rf build_voicevox
-          rm -rf download
+          git clone -b "${{ matrix.voicevox_core_example_version }}" --depth 1 "https://github.com/Hiroshiba/voicevox_core.git" download/voicevox_core_example
+
+      - name: Install dependencies for building VOICEVOX Core Python package
+        if: steps.venv-build-voicevox-cache.outputs.cache-hit != 'true'
+        shell: bash
+        run: |
+          source build_voicevox/bin/activate
+          pip install -r download/voicevox_core_example/example/python/requirements.txt
+          deactivate
+
+      - name: Install VOICEVOX Core Python package
+        if: steps.venv-build-voicevox-cache.outputs.cache-hit != 'true'
+        shell: bash
+        run: |
+          source build_voicevox/bin/activate
+          NUMPY_INCLUDE=`python -c "import numpy; print(numpy.get_include())"`
+          cp download/voicevox_core_example/core.h download/voicevox_core_example/example/python/
+
+          CPATH="$NUMPY_INCLUDE:${CPATH:-}" pip install download/voicevox_core_example/example/python/
+          deactivate
+
+      - name: Install dependencies for building VOICEVOX engine
+        if: steps.venv-build-voicevox-cache.outputs.cache-hit != 'true'
+        shell: bash
+        run: |
+          source build_voicevox/bin/activate
+          pip install -r requirements-dev.txt
+          deactivate
+
+      - name: Download PyOpenJTalk dictionary
+        shell: bash
+        run: |
+          source build_voicevox/bin/activate
+          # Download pyopenjtalk dictionary
+          # try 5 times, sleep 5 seconds before retry
+          for i in $(seq 5); do
+            EXIT_CODE=0
+            python -c "import pyopenjtalk; pyopenjtalk._lazy_init()" || EXIT_CODE=$?
+
+            if [ "$EXIT_CODE" = "0" ]; then
+              break
+            fi
+
+            sleep 5
+          done
+
+          if [ "$EXIT_CODE" != "0" ]; then
+            exit "$EXIT_CODE"
+          fi
+          deactivate
+
+      - name: Build run.py
+        run: |
+          source ../build_voicevox/bin/activate
+          python -m nuitka \
+            --output-dir=./ \
+            --standalone \
+            --plugin-enable=numpy \
+            --follow-import-to=numpy \
+            --follow-import-to=aiofiles \
+            --include-package=uvicorn \
+            --include-package=anyio \
+            --include-package-data=pyopenjtalk \
+            --include-package-data=resampy \
+            --include-package-data=llvmlite \
+            --include-data-file=../VERSION.txt=./ \
+            --include-data-file=../licenses.json=./ \
+            --include-data-file=$(brew --prefix libtorch)/lib/*.dylib=./ \
+            --include-data-file=../download/core/*.dylib=./ \
+            --include-data-file=../download/core/*.bin=./ \
+            --include-data-file=../download/core/metas.json=./ \
+            --include-data-file=$BASE_DIR/build_env/lib/python*/site-packages/scipy/.dylibs/*.dylib=./scipy/.dylibs/ \
+            --include-data-file=../build_voicevox/lib/python*/site-packages/llvmlite/binding/*.dylib=./ \
+            --include-data-file=../build_voicevox/lib/python*/site-packages/_soundfile_data/*=./_soundfile_data/ \
+            --follow-imports \
+            --no-prefer-source-code \
+            ../run.py
+          deactivate
+        working-directory: build
+
+      - name: Set @rpath to @executable_path
+        run: |
+          install_name_tool -add_rpath @executable_path/. build/run.dist/run
+
+      # FIXME: versioned name may be useful; but
+      # actions/download-artifact and dawidd6/download-artifact do not support
+      # wildcard / forward-matching yet.
+      # Currently, It is good to use static artifact name for future binary test workflow.
+      # https://github.com/actions/toolkit/blob/ea81280a4d48fb0308d40f8f12ae00d117f8acb9/packages/artifact/src/internal/artifact-client.ts#L147
+      # https://github.com/dawidd6/action-download-artifact/blob/af92a8455a59214b7b932932f2662fdefbd78126/main.js#L113
+      - uses: actions/upload-artifact@v2
+        # env:
+        #   VERSIONED_ARTIFACT_NAME: |
+        #     ${{ format('{0}-{1}', matrix.artifact_name, (github.event.release.tag_name != '' && github.event.release.tag_name) || github.sha) }}
+        with:
+          name: ${{ matrix.artifact_name }}
+          path: build/run.dist/
+
 
   # Build Linux binary (push only buildcache image)
   build-linux:
