chore: 共通処理をループの外に出す

diff --git a/.github/workflows/build-engine-container.yml b/.github/workflows/build-engine-container.yml
--- a/.github/workflows/build-engine-container.yml
+++ b/.github/workflows/build-engine-container.yml
@@ -294,31 +294,30 @@ jobs:
   
       - name: <Build> Create Manifest lists
         run: |
+          # NOTE: amd64_image_tag, arm64_image_tagの指すイメージが、単一プラットフォームイメージ1つを含むマニフェストリストであることを前提とする
           manifest_list_tags="${{ steps.generate-manifest-docker-manifest-list-names.outputs.manifest_list_tags }}"
           amd64_image_tag="${{ steps.generate-amd64-docker-image-name.outputs.amd64_image_tag }}"
           arm64_image_tag="${{ steps.generate-arm64-docker-image-name.outputs.arm64_image_tag }}"
 
+          # build-dockerでビルドしたマニフェストリストのタグを除くイメージ名を取得
+          amd64_image_name=$(echo "${amd64_image_tag}" | cut -d: -f1)
+          arm64_image_name=$(echo "${arm64_image_tag}" | cut -d: -f1)
+
+          # build-dockerでビルドしたマニフェストリストから、sha256:digest 形式の単一プラットフォームイメージのダイジェストを取得
+          amd64_image_digest=$(docker manifest inspect "${amd64_image_tag}" | jq -r '.manifests[] | select(.platform.architecture=="amd64") | .digest')
+          if [ -z "${amd64_image_digest}" ]; then
+            echo "::error::AMD64イメージのダイジェストを取得できませんでした"
+            exit 1
+          fi
+
+          arm64_image_digest=$(docker manifest inspect "${arm64_image_tag}" | jq -r '.manifests[] | select(.platform.architecture=="arm64") | .digest')
+          if [ -z "${arm64_image_digest}" ]; then
+            echo "::error::ARM64イメージのダイジェストを取得できませんでした"
+            exit 1
+          fi
+
           IFS=$'\n'
           for manifest_list_tag in $manifest_list_tags; do
-            # NOTE: amd64_image_tag, arm64_image_tagの指すイメージが、単一プラットフォームイメージ1つを含むマニフェストリストであることを前提とする
-
-            # build-dockerでビルドしたマニフェストリストのタグを除くイメージ名を取得
-            amd64_image_name=$(echo "${amd64_image_tag}" | cut -d: -f1)
-            arm64_image_name=$(echo "${arm64_image_tag}" | cut -d: -f1)
-
-            # build-dockerでビルドしたマニフェストリストから、sha256:digest 形式の単一プラットフォームイメージのダイジェストを取得
-            amd64_image_digest=$(docker manifest inspect "${amd64_image_tag}" | jq -r '.manifests[] | select(.platform.architecture=="amd64") | .digest')
-            if [ -z "${amd64_image_digest}" ]; then
-              echo "::error::AMD64イメージのダイジェストを取得できませんでした"
-              exit 1
-            fi
-
-            arm64_image_digest=$(docker manifest inspect "${arm64_image_tag}" | jq -r '.manifests[] | select(.platform.architecture=="arm64") | .digest')
-            if [ -z "${arm64_image_digest}" ]; then
-              echo "::error::ARM64イメージのダイジェストを取得できませんでした"
-              exit 1
-            fi
-
             # イメージ名とダイジェストを指定して、新規のマニフェストリストを作成
             docker manifest create \
               "${manifest_list_tag}" \
