ci: prepare_python, test をuvに対応させる

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -23,43 +23,44 @@ jobs:
       - name: <Setup> Prepare Python Runtime / Python Dependencies
         uses: ./.github/actions/prepare_python
         with:
-          requirements-suffix: "-dev"
+          requirements-suffix: dev
 
-      - name: <Test> Validate poetry.lock
-        run: |
-          poetry lock
-          git diff --exit-code
+      # TODO: ここは後でどうするか考える
+      # - name: <Test> Validate poetry.lock
+      #   run: |
+      #     poetry lock
+      #     git diff --exit-code
 
-      - name: <Test> Check dependency lists
-        run: |
-          poetry export --without-hashes -o requirements.txt.check
-          poetry export --without-hashes --with dev -o requirements-dev.txt.check
-          poetry export --without-hashes --with build -o requirements-build.txt.check
+      # - name: <Test> Check dependency lists
+      #   run: |
+      #     poetry export --without-hashes -o requirements.txt.check
+      #     poetry export --without-hashes --with dev -o requirements-dev.txt.check
+      #     poetry export --without-hashes --with build -o requirements-build.txt.check
 
-          diff -q requirements.txt requirements.txt.check || \
-          diff -q requirements-dev.txt requirements-dev.txt.check || \
-          diff -q requirements-build.txt requirements-build.txt.check > /dev/null
-          if [ $? = 1 ]; then
-            echo "poetry export has some diff"
-            exit 1
-          fi
+      #     diff -q requirements.txt requirements.txt.check || \
+      #     diff -q requirements-dev.txt requirements-dev.txt.check || \
+      #     diff -q requirements-build.txt requirements-build.txt.check > /dev/null
+      #     if [ $? = 1 ]; then
+      #       echo "poetry export has some diff"
+      #       exit 1
+      #     fi
 
       - name: <Test> Check linting
-        run: ruff check
+        run: uv run ruff check
 
       - name: <Test> Check formatting
-        run: ruff format --check
+        run: uv run ruff format --check
 
       - name: <Test> Check typing
-        run: mypy .
+        run: uv run mypy .
 
       - name: <Test> Test codes and coverage
-        run: coverage run --omit=test/* -m pytest
+        run: uv run coverage run --omit=test/* -m pytest
 
       - name: <Deploy> Submit coverage results to Coveralls
         if: runner.os == 'Linux'
         # Coveralls へのアップロードが失敗しても CI は継続させる
-        run: coveralls --service=github || echo "::warning::Coveralls failed, but continuing"
+        run: uv run coveralls --service=github || echo "::warning::Coveralls failed, but continuing"
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
