ci: coverallsへアップロードが失敗してもCIを止めないようにする

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -52,7 +52,8 @@ jobs:
 
       - name: <Deploy> Submit coverage results to Coveralls
         if: runner.os == 'Linux'
-        run: coveralls --service=github
+        # Coveralls にアップロード失敗してもCIは継続させる
+        run: coveralls --service=github || echo "Coveralls upload failed, but continuing"
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
